### ISSUE TITLE
No weather found

### ISSUE THREAD

**Issue by richardHaggioGwati** [DenverCoder1/weather-app-tutorial#1]
Does not work.

Errors recieved
Failed to load resource: the server responded with a status of 401 (Unauthorized)
Uncaught (in promise) Error: No weather found.

Props for the changing background..

**Comment by DenverCoder1** [comment]
401 means you don't have a valid API key.

See https://openweathermap.org/faq#error401 for more info.

https://github.com/DenverCoder1/weather-app-tutorial/blob/602e3b466bf695200373bdacd50bfa6de792ac0d/script.js#L1-L3

**Comment by richardHaggioGwati** [comment]
Thanks let me try

**Comment by FrostyFeet-coder** [comment]
didnt worked

Uncaught (in promise) TypeError: Cannot destructure property 'icon' of 'data.weather' as it is undefined.
    at Object.DisplayWeather (scipt.js:14:16)
    at scipt.js:10:28
